# Generated by Django 5.0.1 on 2025-11-09 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("SUBMITTED", "Submitted"),
                            ("GRADED", "Graded"),
                            ("LATE", "Late Submission"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                ("submission_text", models.TextField(blank=True, null=True)),
                (
                    "submission_file",
                    models.FileField(
                        blank=True, null=True, upload_to="homework_submissions/"
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=10, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Homework",
                "verbose_name_plural": "Homework Assignments",
                "db_table": "homework",
                "ordering": ["-assigned_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "udise_student_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique UDISE Student ID (Required - 21 digits)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "roll_no",
                    models.CharField(
                        blank=True, help_text="Roll number", max_length=50, null=True
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 10 (legacy field, use current_class instead)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="e.g., A, B, C (legacy field, use current_class instead)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "parent_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "parent_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "ai_quota_limit",
                    models.IntegerField(
                        default=100, help_text="Monthly AI query quota"
                    ),
                ),
                ("ai_quota_used", models.IntegerField(default=0)),
                ("ai_quota_reset_date", models.DateField(blank=True, null=True)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2024-2025'",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "db_table": "student_profiles",
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-2025'", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_grade",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("attendance_percentage", models.FloatField(default=0.0)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Subject Enrollment",
                "verbose_name_plural": "Student Subject Enrollments",
                "db_table": "student_subjects",
            },
        ),
    ]
