# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("superadmin", "0001_initial"),
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_homework",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_assignments",
                to="superadmin.subject",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Current class/grade the student is enrolled in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="superadmin.class",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="The school this student belongs to (assigned during approval)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="superadmin.school",
            ),
        ),
    ]
