# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_initial"),
        ("superadmin", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_enrollments",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="superadmin.subject",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_subject_teachings",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["udise_student_id"], name="student_pro_udise_s_b55235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["school"], name="student_pro_school__ed3de5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["current_class"], name="student_pro_current_a3a5ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(
                fields=["student", "-assigned_date"], name="homework_student_7dc9b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(fields=["status"], name="homework_status_68b5d2_idx"),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(fields=["subject"], name="homework_subject_ad3caa_idx"),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["student", "subject"], name="student_sub_student_19a012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["academic_year"], name="student_sub_academi_c3be21_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentsubject",
            unique_together={("student", "subject", "academic_year")},
        ),
    ]
