# Generated by Django 5.0.1 on 2025-11-09 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("can_add_teachers", models.BooleanField(default=True)),
                ("can_remove_teachers", models.BooleanField(default=True)),
                ("can_add_students", models.BooleanField(default=True)),
                ("can_approve_ai_quota", models.BooleanField(default=True)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_broadcast_announcements", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
                "db_table": "admin_profiles",
            },
        ),
    ]
