# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="school",
            field=models.ForeignKey(
                help_text="School this admin manages",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="superadmin.school",
            ),
        ),
    ]
