# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(
                fields=["employee_id"], name="admin_profi_employe_61008f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminprofile",
            index=models.Index(
                fields=["school"], name="admin_profi_school__d7a931_idx"
            ),
        ),
    ]
