# Generated by Django 5.2.8 on 2025-12-06 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_initial"),
        ("superadmin", "0003_add_announcement_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSchool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the admin's primary school?"
                    ),
                ),
                ("can_add_teachers", models.BooleanField(default=True)),
                ("can_remove_teachers", models.BooleanField(default=True)),
                ("can_add_students", models.BooleanField(default=True)),
                ("can_approve_ai_quota", models.BooleanField(default=True)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_broadcast_announcements", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Admin School Assignment",
                "verbose_name_plural": "Admin School Assignments",
                "db_table": "admin_schools",
            },
        ),
        migrations.RemoveIndex(
            model_name="adminprofile",
            name="admin_profi_school__d7a931_idx",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="school",
        ),
        migrations.AddField(
            model_name="adminschool",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_schools",
                to="admins.adminprofile",
            ),
        ),
        migrations.AddField(
            model_name="adminschool",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_admins",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="schools",
            field=models.ManyToManyField(
                help_text="Schools this admin manages",
                related_name="admins",
                through="admins.AdminSchool",
                to="superadmin.school",
            ),
        ),
        migrations.AddIndex(
            model_name="adminschool",
            index=models.Index(
                fields=["admin", "school"], name="admin_schoo_admin_i_ffca7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminschool",
            index=models.Index(
                fields=["school"], name="admin_schoo_school__08d55f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminschool",
            unique_together={("admin", "school")},
        ),
    ]
