# Generated by Django 5.0.1 on 2025-11-09 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "model_used",
                    models.CharField(default="gpt-3.5-turbo", max_length=100),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AI Chat Session",
                "verbose_name_plural": "AI Chat Sessions",
                "db_table": "ai_chat_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMachineProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        db_index=True,
                        help_text="API Key for AI service",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("service_version", models.CharField(default="1.0.0", max_length=50)),
                ("is_online", models.BooleanField(default=False)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Machine Profile",
                "verbose_name_plural": "AI Machine Profiles",
                "db_table": "ai_machine_profiles",
            },
        ),
        migrations.CreateModel(
            name="AIUsageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_queries", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.IntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("error_count", models.IntegerField(default=0)),
                ("date", models.DateField(db_index=True)),
                (
                    "hour",
                    models.IntegerField(
                        blank=True, help_text="Hour of day (0-23)", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Metric",
                "verbose_name_plural": "AI Usage Metrics",
                "db_table": "ai_usage_metrics",
                "ordering": ["-date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ASSISTANT", "Assistant"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
