# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_machine", "0002_initial"),
        ("superadmin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aimachineprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_machine_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiusagemetrics",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for platform-level metrics",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_metrics",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai_machine.aichatsession",
            ),
        ),
        migrations.AddIndex(
            model_name="aichatsession",
            index=models.Index(
                fields=["student", "-started_at"], name="ai_chat_ses_student_3e45c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aichatsession",
            index=models.Index(
                fields=["session_token"], name="ai_chat_ses_session_fe9bc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagemetrics",
            index=models.Index(
                fields=["-date", "school"], name="ai_usage_me_date_c51b94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiusagemetrics",
            unique_together={("school", "date", "hour")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_messag_session_597c4e_idx"
            ),
        ),
    ]
