# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the teacher's primary subject?",
                    ),
                ),
                (
                    "years_teaching",
                    models.IntegerField(
                        default=0, help_text="Years teaching this subject"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Teacher Subject",
                "verbose_name_plural": "Teacher Subjects",
                "db_table": "teacher_subjects",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="superadmin.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
                "db_table": "attendance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TeacherClassAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-2025'", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="superadmin.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_assignments",
                        to="superadmin.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Class Assignment",
                "verbose_name_plural": "Teacher Class Assignments",
                "db_table": "teacher_class_assignments",
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room_number", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="teachers.teacherclassassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Schedule",
                "verbose_name_plural": "Class Schedules",
                "db_table": "class_schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique employee ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "primary_subject",
                    models.CharField(
                        blank=True,
                        help_text="Primary subject taught (legacy field)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        default=0, help_text="Years of teaching experience"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True, default=list, help_text="List of certifications"
                    ),
                ),
                ("can_mark_attendance", models.BooleanField(default=True)),
                ("can_assign_homework", models.BooleanField(default=True)),
                ("can_grade_assignments", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profiles",
                        to="superadmin.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Profile",
                "verbose_name_plural": "Teacher Profiles",
                "db_table": "teacher_profiles",
            },
        ),
    ]
