# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("superadmin", "0002_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherclassassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_assignments",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendance",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_teachers",
                to="superadmin.subject",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_subjects",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="subjects",
            field=models.ManyToManyField(
                help_text="Subjects taught by this teacher",
                related_name="teachers",
                through="teachers.TeacherSubject",
                to="superadmin.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["teacher_assignment", "day_of_week"],
                name="class_sched_teacher_399a6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherclassassignment",
            index=models.Index(
                fields=["teacher", "school_class"],
                name="teacher_cla_teacher_b451b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherclassassignment",
            index=models.Index(
                fields=["school_class", "subject"],
                name="teacher_cla_school__280ab4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherclassassignment",
            index=models.Index(
                fields=["academic_year"], name="teacher_cla_academi_e37723_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherclassassignment",
            unique_together={("school_class", "subject", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "-date"], name="attendance_student_687d28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["school_class", "date"], name="attendance_school__de4ac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "status"], name="attendance_date_32df9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["teacher", "subject"], name="teacher_sub_teacher_16bdcb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachersubject",
            unique_together={("teacher", "subject")},
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["employee_id"], name="teacher_pro_employe_3664a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["school"], name="teacher_pro_school__76c144_idx"
            ),
        ),
    ]
