# Generated by Django 5.0.1 on 2025-12-06 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0003_add_announcement_target"),
        ("teachers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_teacher_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_teacher_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_tasks",
                        to="superadmin.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="teachers.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Task",
                "verbose_name_plural": "Teacher Tasks",
                "db_table": "teacher_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherTaskReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "reply_type",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Teacher Reply"),
                            ("ADMIN", "Admin Reply"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_task_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="teachers.teachertask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Task Reply",
                "verbose_name_plural": "Teacher Task Replies",
                "db_table": "teacher_task_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public Holiday"),
                            ("SCHOOL", "School Holiday"),
                            ("EXAM", "Exam Period"),
                            ("VACATION", "Vacation"),
                            ("OTHER", "Other"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="superadmin.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "School Holiday",
                "verbose_name_plural": "School Holidays",
                "db_table": "school_holidays",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["school", "date"], name="school_holi_school__5fc079_idx"
                    )
                ],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="teachertask",
            index=models.Index(
                fields=["teacher", "status"], name="teacher_tas_teacher_f4cf9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachertask",
            index=models.Index(
                fields=["school", "status"], name="teacher_tas_school__9925fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachertask",
            index=models.Index(
                fields=["assigned_by", "-created_at"],
                name="teacher_tas_assigne_ed3066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachertask",
            index=models.Index(
                fields=["-created_at"], name="teacher_tas_created_a89e2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachertaskreply",
            index=models.Index(
                fields=["task", "created_at"], name="teacher_tas_task_id_ad252f_idx"
            ),
        ),
    ]
