# Generated by Django 5.0.1 on 2025-12-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0003_add_announcement_target"),
        ("teachers", "0003_add_teacher_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="attendance_class",
            field=models.ForeignKey(
                blank=True,
                help_text="The class this teacher is assigned to take attendance for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_teachers",
                to="superadmin.class",
            ),
        ),
    ]
