# Generated by Django 5.0.1 on 2025-12-14 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_initial"),
        ("superadmin", "0006_schoolclass_alter_class_options_and_more"),
        ("teachers", "0006_add_student_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("CLASS", "Class Level"),
                            ("STUDENT", "Student Level"),
                        ],
                        default="CLASS",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "google_meet_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("zoom_link", models.URLField(blank=True, max_length=500, null=True)),
                ("other_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "link_label",
                    models.CharField(
                        blank=True,
                        help_text="Label for other_link",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivitySubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Student's response/answer", null=True
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("COMPLETED", "Completed"),
                            ("LATE", "Late Submission"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Activity Submission",
                "verbose_name_plural": "Activity Submissions",
                "db_table": "activity_submissions",
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="studenttask",
            new_name="student_tas_student_728d73_idx",
            old_name="student_tas_student_9e8e99_idx",
        ),
        migrations.RenameIndex(
            model_name="studenttask",
            new_name="student_tas_created_7419b2_idx",
            old_name="student_tas_created_1d4c95_idx",
        ),
        migrations.RenameIndex(
            model_name="studenttask",
            new_name="student_tas_school__490dcb_idx",
            old_name="student_tas_school__f9a8f5_idx",
        ),
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_activities",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="superadmin.class",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_activities",
                to="students.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="superadmin.subject",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="teachers.activity",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="activitysubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_submissions",
                to="students.studentprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["school_class", "-created_at"],
                name="activities_school__7c8f3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["school", "-created_at"], name="activities_school__e7cb31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="activities_created_eb8266_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["level", "status"], name="activities_level_8a4cbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["scheduled_date"], name="activities_schedul_38a822_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysubmission",
            index=models.Index(
                fields=["activity", "status"], name="activity_su_activit_db102b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysubmission",
            index=models.Index(
                fields=["student", "-created_at"], name="activity_su_student_82e737_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitysubmission",
            index=models.Index(fields=["status"], name="activity_su_status_1367aa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="activitysubmission",
            unique_together={("activity", "student")},
        ),
    ]
