# Generated by Django 5.0.1 on 2025-12-29 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0007_activity_activitysubmission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTaskReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "reply_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student Reply"),
                            ("TEACHER", "Teacher Reply"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_task_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="teachers.studenttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Task Reply",
                "verbose_name_plural": "Student Task Replies",
                "db_table": "student_task_replies",
                "ordering": ["created_at"],
            },
        ),
    ]
