# Generated by Django 5.0.1 on 2025-12-29 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_initial"),
        ("superadmin", "0009_add_student_task_reply_and_schemes"),
        ("teachers", "0008_add_student_task_reply_and_schemes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Half Yearly Exam 2024", max_length=255
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("EXAM", "Exam Report"),
                            ("PROGRESS", "Progress Report"),
                            ("ASSESSMENT", "Assessment"),
                            ("QUARTERLY", "Quarterly Report"),
                            ("HALF_YEARLY", "Half Yearly Report"),
                            ("ANNUAL", "Annual Report"),
                            ("OTHER", "Other"),
                        ],
                        default="EXAM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(default="2024-2025", max_length=20)),
                ("exam_date", models.DateField(blank=True, null=True)),
                (
                    "subjects",
                    models.JSONField(
                        default=list,
                        help_text="List of subject objects: [{id, name, max_marks}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "class_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="superadmin.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to="teachers.teacherprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="superadmin.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentMark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marks",
                    models.JSONField(
                        default=dict,
                        help_text="Subject-wise marks: {subject_id: {marks: 85, max_marks: 100}}",
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "total_max_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("grade", models.CharField(blank=True, max_length=5, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_marks",
                        to="teachers.report",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_marks",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Mark",
                "verbose_name_plural": "Student Marks",
                "db_table": "student_marks",
                "ordering": ["-percentage", "student__roll_no"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["school", "class_ref", "-created_at"],
                name="reports_school__83ca22_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="reports_status_d7deb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "academic_year"],
                name="reports_report__7e494f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmark",
            index=models.Index(
                fields=["report", "-percentage"], name="student_mar_report__116180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmark",
            index=models.Index(
                fields=["student", "-created_at"], name="student_mar_student_7e2bed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together={("report", "student")},
        ),
    ]
