# Generated by Django 5.0.1 on 2025-11-09 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of roles: ['STUDENT', 'TEACHER', 'ADMIN']",
                    ),
                ),
                (
                    "target_states",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of states. Leave empty for all states",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "db_table": "announcements",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Class name (e.g., '10th Standard', 'Class 5')",
                        max_length=50,
                    ),
                ),
                ("grade", models.IntegerField(help_text="Grade number (1-12)")),
                (
                    "section",
                    models.CharField(
                        help_text="Section (e.g., 'A', 'B', 'C')", max_length=10
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "max_students",
                    models.IntegerField(
                        default=40, help_text="Maximum student capacity"
                    ),
                ),
                (
                    "current_students",
                    models.IntegerField(
                        default=0, help_text="Current number of students"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g., '2024-2025'", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "db_table": "classes",
                "ordering": ["school", "grade", "section"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("new_users_today", models.IntegerField(default=0)),
                ("pending_users", models.IntegerField(default=0)),
                ("total_schools", models.IntegerField(default=0)),
                ("active_schools", models.IntegerField(default=0)),
                ("new_schools_today", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("total_admins", models.IntegerField(default=0)),
                ("total_superadmins", models.IntegerField(default=0)),
                ("total_ai_queries_today", models.BigIntegerField(default=0)),
                ("total_tokens_consumed_today", models.BigIntegerField(default=0)),
                ("average_tokens_per_query", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform Analytics",
                "verbose_name_plural": "Platform Analytics",
                "db_table": "platform_analytics",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the school", max_length=255
                    ),
                ),
                (
                    "udise_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique District Information System for Education code (11 digits)",
                        max_length=11,
                        unique=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "principal_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "board",
                    models.CharField(
                        blank=True,
                        help_text="e.g., CBSE, ICSE, State Board",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "ai_quota_limit",
                    models.IntegerField(
                        default=100000,
                        help_text="Monthly AI token quota for the entire school",
                    ),
                ),
                ("ai_quota_used", models.IntegerField(default=0)),
                ("ai_quota_reset_date", models.DateField(blank=True, null=True)),
                (
                    "total_students",
                    models.IntegerField(
                        default=0, help_text="Total number of students"
                    ),
                ),
                (
                    "total_teachers",
                    models.IntegerField(
                        default=0, help_text="Total number of teachers"
                    ),
                ),
                (
                    "total_admins",
                    models.IntegerField(default=0, help_text="Total number of admins"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_in_school",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("left_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School User",
                "verbose_name_plural": "School Users",
                "db_table": "school_users",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name (e.g., Mathematics)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code (e.g., MATH101)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CORE", "Core Subject"),
                            ("ELECTIVE", "Elective"),
                            ("VOCATIONAL", "Vocational"),
                            ("EXTRA_CURRICULAR", "Extra-Curricular"),
                        ],
                        default="CORE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SuperAdminProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "admin_level",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National Level"),
                            ("STATE", "State Level"),
                            ("REGIONAL", "Regional Level"),
                        ],
                        default="REGIONAL",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region/zone/state this super admin manages",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("can_create_admins", models.BooleanField(default=True)),
                ("can_create_teachers", models.BooleanField(default=True)),
                ("can_delete_users", models.BooleanField(default=True)),
                ("can_manage_schools", models.BooleanField(default=True)),
                ("can_view_platform_analytics", models.BooleanField(default=True)),
                ("can_manage_system_settings", models.BooleanField(default=True)),
                ("can_send_announcements", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Super Admin Profile",
                "verbose_name_plural": "Super Admin Profiles",
                "db_table": "superadmin_profiles",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "setting_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("setting_value", models.TextField()),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON"),
                        ],
                        default="STRING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "ordering": ["setting_key"],
            },
        ),
    ]
