# Generated by Django 5.0.1 on 2025-11-09 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("superadmin", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Class teacher/homeroom teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_classes",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="platformanalytics",
            index=models.Index(
                fields=["-snapshot_date"], name="platform_an_snapsho_081112_idx"
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_schools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_schools",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty for all schools",
                related_name="announcements",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="schooluser",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_users",
                to="superadmin.school",
            ),
        ),
        migrations.AddField(
            model_name="schooluser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_schools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="subjects_code_3f80fa_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["category"], name="subjects_categor_8c1690_idx"),
        ),
        migrations.AddField(
            model_name="superadminprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="superadmin_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_settings_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["udise_code"], name="schools_udise_c_dd1734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["district", "state"], name="schools_distric_2758ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["status"], name="schools_status_0f17fc_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["state"], name="schools_state_6d03ec_idx"),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school", "grade"], name="classes_school__481404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school", "academic_year"], name="classes_school__ab7f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["grade", "section"], name="classes_grade_34e372_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("school", "grade", "section", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["-published_at"], name="announcemen_publish_4a0d1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["status", "is_active"], name="announcemen_status_2f7d97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schooluser",
            index=models.Index(
                fields=["school", "user"], name="school_user_school__7b1be8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schooluser",
            index=models.Index(
                fields=["school", "role_in_school"],
                name="school_user_school__38ca5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schooluser",
            index=models.Index(fields=["user"], name="school_user_user_id_8c7d83_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="schooluser",
            unique_together={("school", "user")},
        ),
    ]
