# Generated by Django 5.2.8 on 2025-12-06 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="target_roles",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="target_schools",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="target_states",
        ),
        migrations.CreateModel(
            name="AnnouncementTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="For school targets: filter by roles ['STUDENT', 'TEACHER', 'ADMIN']",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="superadmin.announcement",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target all users in this school (school-level)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_targets",
                        to="superadmin.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target this specific user (user-level)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement Target",
                "verbose_name_plural": "Announcement Targets",
                "db_table": "announcement_targets",
                "indexes": [
                    models.Index(
                        fields=["announcement", "school"],
                        name="announcemen_announc_78e262_idx",
                    ),
                    models.Index(
                        fields=["announcement", "user"],
                        name="announcemen_announc_5ed135_idx",
                    ),
                    models.Index(
                        fields=["school"], name="announcemen_school__d5ba80_idx"
                    ),
                    models.Index(
                        fields=["user"], name="announcemen_user_id_4d85af_idx"
                    ),
                    models.Index(
                        fields=["is_sent"], name="announcemen_is_sent_d48036_idx"
                    ),
                ],
                "unique_together": {("announcement", "school", "user")},
            },
        ),
    ]
