# Generated by Django 5.0.1 on 2025-12-14 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0005_refactor_class_models"),
        ("teachers", "0006_add_student_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section (e.g., 'A', 'B', 'C')",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "max_students",
                    models.IntegerField(
                        default=40, help_text="Maximum student capacity"
                    ),
                ),
                (
                    "current_students",
                    models.IntegerField(
                        default=0, help_text="Current number of students"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        default="2024-2025",
                        help_text="e.g., '2024-2025'",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Class",
                "verbose_name_plural": "School Classes",
                "db_table": "school_classes",
                "ordering": ["school", "class_obj__grade_number", "section"],
            },
        ),
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["grade_number"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.RemoveIndex(
            model_name="class",
            name="classes_school__481404_idx",
        ),
        migrations.RemoveIndex(
            model_name="class",
            name="classes_school__ab7f87_idx",
        ),
        migrations.RemoveIndex(
            model_name="class",
            name="classes_grade_34e372_idx",
        ),
        migrations.RenameIndex(
            model_name="classsubject",
            new_name="class_subje_class_o_1ee343_idx",
            old_name="class_subject_class_subj_6fb28d_idx",
        ),
        migrations.RenameIndex(
            model_name="classsubject",
            new_name="class_subje_subject_c89190_idx",
            old_name="class_subject_subject__caa0b0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="class",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="grade_number",
            field=models.IntegerField(
                default=1, help_text="Grade/Class number (1-12)", unique=True
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="credits",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="is_mandatory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="weekly_hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                help_text="Display name (e.g., 'Class 5', '5th Standard')",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects taught in this class",
                related_name="classes",
                through="superadmin.ClassSubject",
                to="superadmin.subject",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_classes",
                to="superadmin.class",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Class teacher/homeroom teacher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_classes",
                to="teachers.teacherprofile",
            ),
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_classes",
                to="superadmin.school",
            ),
        ),
        migrations.RemoveField(
            model_name="class",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="class",
            name="class_teacher",
        ),
        migrations.RemoveField(
            model_name="class",
            name="current_students",
        ),
        migrations.RemoveField(
            model_name="class",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="class",
            name="max_students",
        ),
        migrations.RemoveField(
            model_name="class",
            name="room_number",
        ),
        migrations.RemoveField(
            model_name="class",
            name="school",
        ),
        migrations.RemoveField(
            model_name="class",
            name="section",
        ),
        migrations.AlterUniqueTogether(
            name="schoolclass",
            unique_together={("school", "class_obj", "section", "academic_year")},
        ),
    ]
