# Generated by Django 5.0.1 on 2025-12-14 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0006_schoolclass_alter_class_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="announcementtarget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="announcementtarget",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Target all students in this class (class-level)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcement_targets",
                to="superadmin.schoolclass",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementtarget",
            index=models.Index(
                fields=["announcement", "school_class"],
                name="announcemen_announc_3c8669_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementtarget",
            index=models.Index(
                fields=["school_class"], name="announcemen_school__a6a660_idx"
            ),
        ),
    ]
