# Generated by Django 5.0.1 on 2025-12-29 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0008_add_news_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "scheme_type",
                    models.CharField(
                        choices=[
                            ("EXAM", "Competitive Exam"),
                            ("SCHOLARSHIP", "Scholarship"),
                            ("EVENT", "Event"),
                            ("PROGRAM", "Government Program"),
                            ("COMPETITION", "Competition"),
                            ("ADMISSION", "Admission"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "eligibility",
                    models.TextField(
                        blank=True, help_text="Who can apply/participate", null=True
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Documents or prerequisites needed",
                        null=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Start date of the scheme/exam", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date or deadline", null=True
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                (
                    "official_link",
                    models.URLField(
                        blank=True,
                        help_text="Official website or registration link",
                        null=True,
                    ),
                ),
                (
                    "apply_link",
                    models.URLField(
                        blank=True, help_text="Direct application link", null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "target_classes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of class names that this scheme is for (e.g., ['Class 10', 'Class 12']). Empty means all classes.",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schemes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Government Scheme",
                "verbose_name_plural": "Government Schemes",
                "db_table": "government_schemes",
                "ordering": ["-priority", "-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheme_type"],
                        name="government__status_ccd176_idx",
                    ),
                    models.Index(
                        fields=["application_deadline"],
                        name="government__applica_856b5d_idx",
                    ),
                    models.Index(
                        fields=["-priority", "-published_at"],
                        name="government__priorit_37a2a4_idx",
                    ),
                ],
            },
        ),
    ]
