# Generated by Django 5.0.1 on 2026-01-03 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0009_add_student_task_reply_and_schemes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_admin_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_tasks",
                        to="superadmin.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Task",
                "verbose_name_plural": "Admin Tasks",
                "db_table": "admin_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminTaskReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_task_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="superadmin.admintask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Task Reply",
                "verbose_name_plural": "Admin Task Replies",
                "db_table": "admin_task_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="admintask",
            index=models.Index(
                fields=["status", "priority"], name="admin_tasks_status_322e71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admintask",
            index=models.Index(
                fields=["assigned_to", "status"], name="admin_tasks_assigne_a04be2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admintask",
            index=models.Index(
                fields=["due_date"], name="admin_tasks_due_dat_41ed28_idx"
            ),
        ),
    ]
